# Generated by Django 5.0.8 on 2024-08-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume_user',
            name='country_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_User_country', to='U_auth.country_codes'),
        ),
        migrations.AlterField(
            model_name='costume_user',
            name='user_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_User_lang', to='U_auth.languages'),
        ),
    ]
