# Generated by Django 5.0.8 on 2024-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0002_alter_costume_user_country_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume_user',
            name='country_code',
        ),
    ]
