# Generated by Django 5.0.8 on 2024-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0003_remove_costume_user_country_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='costume_user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='costume_user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
