# Generated by Django 5.0.8 on 2024-08-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0004_alter_costume_user_managers_alter_costume_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
