# Generated by Django 5.0.8 on 2024-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0007_userpersonaldetails_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photos',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
