# Generated by Django 5.0.8 on 2024-08-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0012_costume_user_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume_user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
