# Generated by Django 5.0.8 on 2024-08-31 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0013_costume_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_age', models.IntegerField()),
                ('preferred_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('interests_hobbies', models.TextField(blank=True)),
                ('education_level', models.CharField(max_length=50)),
                ('preferred_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('smoking_habits', models.CharField(choices=[('NS', 'Non-Smoker'), ('S', 'Smoker')], max_length=2)),
                ('drinking_habits', models.CharField(choices=[('ND', 'Non-Drinker'), ('D', 'Drinker')], max_length=2)),
                ('religion', models.CharField(choices=[('CH', 'Christianity'), ('IS', 'Islam'), ('HI', 'Hinduism'), ('BU', 'Buddhism'), ('JE', 'Judaism'), ('SI', 'Sikhism'), ('OT', 'Other')], max_length=2)),
                ('occupation', models.CharField(max_length=255)),
                ('preferred_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='U_auth.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Preference',
                'verbose_name_plural': 'Partner Preferences',
            },
        ),
    ]
