# Generated by Django 5.0.8 on 2024-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0018_remove_userinterests_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='auual_income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='religion',
            field=models.CharField(choices=[('CH', 'Christianity'), ('IS', 'Islam'), ('HI', 'Hinduism'), ('BU', 'Buddhism'), ('JE', 'Judaism'), ('SI', 'Sikhism'), ('OT', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='additionaldetails',
            name='user_disabilitys',
            field=models.ManyToManyField(to='U_auth.disabilities', verbose_name='disabilities'),
        ),
        migrations.DeleteModel(
            name='UserDisabilities',
        ),
    ]
