# Generated by Django 5.0.8 on 2024-09-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0021_alter_additionaldetails_user_alter_job_details_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_and_Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partnerpreference',
            options={},
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='drinking_habits',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='preferred_age',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='preferred_height',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='preferred_weight',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='smoking_habits',
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='age_max',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='age_min',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='height_max',
            field=models.IntegerField(default=220),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='height_min',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='weight_max',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='weight_min',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='interests_hobbies',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='preferred_location',
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='lifestyle_choices',
            field=models.ManyToManyField(to='U_auth.lifestylechoice'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='interests_hobbies',
            field=models.ManyToManyField(to='U_auth.interest_and_hobbie'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='preferred_location',
            field=models.ManyToManyField(to='U_auth.location'),
        ),
    ]
