# Generated by Django 5.0.8 on 2024-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0023_remove_job_details_location_remove_location_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreference',
            name='education_level',
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default_pic.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='education_level',
            field=models.ManyToManyField(to='U_auth.qualifications'),
        ),
    ]
