# Generated by Django 5.0.8 on 2024-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0024_remove_partnerpreference_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldetails',
            name='bio',
            field=models.CharField(blank=True, default='This user hasn’t added a bio yet. Stay tuned for more!', max_length=100),
        ),
    ]
