# Generated by Django 5.0.8 on 2024-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0026_alter_country_codes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='profile_pic',
            field=models.ImageField(default='default_pic.png', upload_to='images/'),
        ),
    ]
