# Generated by Django 5.0.8 on 2024-09-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0027_alter_userpersonaldetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='profile_pic',
            field=models.ImageField(default='user-default-pic/default_pic.png', upload_to='images/'),
        ),
    ]
