# Generated by Django 5.0.8 on 2024-09-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0029_alter_userpersonaldetails_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreference',
            name='interests_hobbies',
        ),
        migrations.RemoveField(
            model_name='partnerpreference',
            name='preferred_location',
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='hobbies',
            field=models.ManyToManyField(to='U_auth.hobbies'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='interests',
            field=models.ManyToManyField(to='U_auth.interests'),
        ),
        migrations.CreateModel(
            name='preferred_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='U_auth.partnerpreference')),
            ],
        ),
        migrations.DeleteModel(
            name='Interest_and_Hobbie',
        ),
    ]
