# Generated by Django 5.0.8 on 2024-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0030_remove_partnerpreference_interests_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldetails',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpersonaldetails',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
