# Generated by Django 5.0.8 on 2024-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0031_userpersonaldetails_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume_user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
