# Generated by Django 5.0.8 on 2024-10-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0032_costume_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume_user',
            name='is_deleted',
        ),
    ]
