# Generated by Django 5.0.8 on 2024-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_interestrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
