# Generated by Django 5.0.8 on 2024-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
