# Generated by Django 5.0.8 on 2024-10-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0002_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
