# Generated by Django 5.0.8 on 2024-10-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0003_alter_chatroom_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='chat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_data', to='U_messages.chatroom'),
        ),
    ]
