# Generated by Django 5.0.8 on 2024-10-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0004_alter_chatinfo_chat_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatinfo',
            name='user_type',
        ),
        migrations.AddField(
            model_name='chatinfo',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiverinfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatinfo',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_senderinfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
