# Generated by Django 5.0.8 on 2024-10-05 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0005_remove_chatinfo_user_remove_chatinfo_user_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('targeted_audiences', models.JSONField()),
                ('target_specific', models.CharField(choices=[('matrimony', 'matrimony'), ('job-portal', 'job-portal'), ('dating', 'dating'), ('ecommerce', 'ecommerce'), ('study-aboard', 'study-aboard')], max_length=15)),
                ('other_service', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('inapp', 'inapp')], max_length=15)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
