# Generated by Django 5.0.8 on 2024-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0006_notificationdetails_notificationroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='notification-images/'),
        ),
    ]
