# Generated by Django 5.0.8 on 2024-10-07 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0030_remove_partnerpreference_interests_hobbies_and_more'),
        ('U_messages', '0008_alter_notificationdetails_targeted_audiences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amidusers',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='U_auth.userpersonaldetails'),
        ),
        migrations.AlterField(
            model_name='amidusers',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
