# Generated by Django 5.0.8 on 2024-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0010_alter_amidusers_locations_alter_amidusers_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification-images/'),
        ),
    ]
