# Generated by Django 5.0.8 on 2024-10-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_messages', '0011_alter_notificationdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetails',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
