# Generated by Django 5.0.8 on 2024-09-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0003_alter_subscription_start_date'),
        ('subscription', '0004_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='matrimony_admin.subscription', verbose_name='sub_plan'),
            preserve_default=False,
        ),
    ]
