# Generated by Django 5.0.8 on 2024-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_payment_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'upi'), ('PayPal', 'PayPal'), ('card', 'card'), ('razorpay', 'razorpay')], default=3, max_length=50),
            preserve_default=False,
        ),
    ]
