# Generated by Django 5.0.8 on 2024-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_payment_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slug_name',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
