# Generated by Django 5.0.8 on 2024-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0003_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
