# Generated by Django 5.0.8 on 2024-09-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0004_subscription_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionINFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matrimony_admin.subscription', verbose_name='sub_info')),
            ],
            options={
                'verbose_name': 'SubscriptionINFO',
                'verbose_name_plural': 'SubscriptionINFOS',
            },
        ),
    ]
