# Generated by Django 5.0.8 on 2024-09-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0005_subscriptioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_admin.subscription', verbose_name='sub_info'),
        ),
    ]
