# Generated by Django 5.0.8 on 2024-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0006_alter_subscriptioninfo_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('premium', 'Premium')], max_length=100),
        ),
    ]
