# Generated by Django 5.0.8 on 2024-09-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0007_alter_subscription_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_info', to='matrimony_admin.subscription'),
        ),
    ]
