# Generated by Django 5.0.8 on 2024-10-09 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrimony_admin", "0010_blockeduserinfo"),
        ("matrimony_admin", "0010_remove_subscription_subscription_type"),
    ]

    operations = []
