# Generated by Django 5.0.8 on 2024-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimony_admin", "0011_merge_20241009_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_expense",
            fields=[
                ("sl_no", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OTHER", "Other"),
                            ("OFFICE", "Office"),
                            ("DARING", "Daring"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=15)),
                ("remark", models.CharField(max_length=15)),
                ("dr", models.IntegerField()),
                ("cr", models.IntegerField()),
                (
                    "invoice",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
            ],
            options={
                "verbose_name": "Add Expense",
                "verbose_name_plural": "Add Expenses",
            },
        ),
    ]
